[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
known_local_folder = "app"

[tool.pytest.ini_options]
testpaths = ["app"]
addopts = "-v -rsxX -l --tb=short --strict --cov=app -p no:warnings"
xfails_strict = true
markers = [
    "tmp",
    "optional",
]